### ISSUE TITLE
I couldn't find any "setup.py" file in the provided materials

### ISSUE THREAD

**Issue by zoughi** [ahlashkari/SCsVulLyzer#1]
Dear Lashkari,

I noticed that in the file, there is a line that says:
"sudo python3 setup.py install"

However, I couldn't find any "setup.py" file in the provided materials.

I would appreciate it if you could take a look and provide further guidance on how to proceed. Please let me know if you have any additional information or instructions.

I'm waiting to hear back from you.

**Comment by Sepid-99** [comment]
Hello Zoughi,
We are currently in the process of developing a standalone package for SCsVulLyzer. 
Unfortunately, it has not been released yet. In the meantime, you may use main.py to apply it to your dataset.

**Comment by Sepid-99** [comment]
Hello Zoughi,
We are currently in the process of developing a standalone package for SCsVulLyzer. 
Unfortunately, it has not been released yet. In the meantime, you may use main.py to apply it to your dataset.
