### ISSUE TITLE
Error Encountered: 'NameError: name 'opcode_list' is not defined'

### ISSUE THREAD

**Issue by zoughi** [ahlashkari/SCsVulLyzer#2]
Hi,

I am writing to inform you about some errors I encountered while running a command in Python. Specifically, when I executed the following command:
```
python main.py path_to_solidity_source_file.sol
```

I received the following error messages:
```
analyzer.py, line 67: NameError: name 'opcode_list' is not defined
analyzer.py, line 67: NameError: name 'keywords_list' is not defined
```
To resolve these issues, you need to define the variables 'opcode_list' and 'keywords_list' before they are used in your code. 

Additionally, I encountered another error:
```
main.py, line 10: NameError: name 'count_keywords_in_text' is not defined
```

Did you mean 'count_keywords_in_code' instead?
Best regards

**Comment by Sepid-99** [comment]
Hello @zoughi,
Thank you for reaching out and identifying this issue. 
The file has been updated to include both the opcode and keyword lists. Additionally, the `count_keywords_in_code` function has been updated in the `main.py` file.

**Comment by Sepid-99** [comment]
Hello @zoughi,
Thank you for reaching out and identifying this issue. 
The file has been updated to include both the opcode and keyword lists. Additionally, the `count_keywords_in_code` function has been updated in the `main.py` file.
